name = "gimletlet-ereportlet"
inherit = "app.toml"

[tasks.jefe.config.allowed-callers]
request_reset = ["hiffy"]

[tasks.hiffy]
features = ["h753", "stm32h7", "i2c", "gpio", "spi"]
task-slots = ["sys", "i2c_driver", "user_leds", "ereportulator"]

[tasks.ereportulator]
name = "task-ereportulator"
priority = 5
start = true
task-slots = ["packrat"]
features = ["fake-vpd"]
notifications = []
