[package]
name = "drv-stm32h7-qspi"
version = "0.1.0"
edition = "2021"

[dependencies]
stm32h7 = { workspace = true }
vcell = { workspace = true }
zerocopy = { workspace = true }

drv-qspi-api = { path = "../qspi-api" }
userlib = { path = "../../sys/userlib" }

counters = { path = "../../lib/counters", optional = true }

[features]
h743 = ["stm32h7/stm32h743"]
h753 = ["stm32h7/stm32h753"]
counters = ["dep:counters"]

[lib]
test = false
doctest = false
bench = false

[lints]
workspace = true
