[package]
name = "drv-sbrmi21"
version = "0.1.0"
edition = "2021"

[dependencies]
apml-rs = { workspace = true }
cfg-if = { workspace = true }
hubpack = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

drv-sbrmi21-api = { path = "../../drv/sbrmi21-api" }
drv-i2c-api = { path = "../../drv/i2c-api" }
drv-i2c-devices = { path = "../../drv/i2c-devices" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api", optional = true }
userlib = { path = "../../sys/userlib" }
ringbuf = { path = "../../lib/ringbuf" }

[build-dependencies]
build-util = { path = "../../build/util" }
build-i2c = { path = "../../build/i2c" }
idol = { workspace = true }

[features]
stm32h7 = ["drv-stm32xx-sys-api/family-stm32h7"]
panic-messages = ["userlib/panic-messages"]

no-ipc-counters = ["idol/no-counters"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-sbrmi21"
test = false
doctest = false
bench = false

[lints]
workspace = true
